export const UNIT = {
    MILE_TO_KILOMETER: 1.609344,
    KILOMETER_TO_MILE: 1 / 1.609344,
    METER_TO_MILE: 1 / (1.609344 * 1000),
};
export const ERROR_CODE = {
    BLOCK_USER: 540,
    WRONG_USERNAME_OR_PASS: 541,
    WAIT_A_DAY: 542,
    USER_DELETED: 543,
    USER_NO_ROLE: 544,
    USER_BLOCKED: 545,
    RECEIVER_NOT_ENOUGH_DOOL: 547,
    ONLY_CELEB: 548,
    RECEIVER_NOT_ALLOW_VIDEO_CALL: 549,

    EXPOSE_TIME_POST_INVALID: 570,

    RESEND_CODE_TOO_MUCH: 580,
    VERIFY_FAIL: 581,
    CODE_EXPIRED: 582,
    NOT_FOUND_PHONE: 583,
    INVALID_PHOTO: 584,

    RATED_USER: 601,
    SENSITIVE_WORD: 602,
    USER_BLOCK_RECEIVER: 510,
    RECEIVER_BLOCK_USER: 509,
    IS_TALKING_CONVERSATION: 605, // CASE TẮT MẠNG R MỞ LÊN LẠI
    ACCEPT_DELETED_CONVERSATION: 606, // CASE CHUẨN BỊ ACCEPT NHƯNG NGƯỜI KIA XÓA CONVERSATION
    BAD_TOKEN: 607,
    EXPIRE_TOKEN: 608,

    // define code
    CONFLICT: 409, // Conflict - if the server will not process a request, but the reason for that is not the client's fault
    NOT_FOUND: 404, // Not found
    BAD_REQUEST: 400, // Bad request
};
export const FCM_ACTIONS = {
    SEND_NOTIFICATION: '0',
    WALLET: '1',
    PRODUCT_VALID: '2',
    PRODUCT_BANNED: '3',
    PRODUCT_EXPIRED: '4',
    PRODUCT_REVIEW: '5',
    BILL: '6',
    EDIT_USER: '7',
    CHAT: '8',
    POST: '9',
    FRIEND: '10',
    GROUP_REQUEST: '11',
    GROUP: '12',
    VNPAY_SUCCESS: '13',
    VNPAY_FAILED: '14',
    BILL_SELL: '15',
    MISSED_CALL: '16',
    RECEIVE_GIFT: '17',
    GIFT: '18',
    BLOCK: '19',
    INTRODUCE_USER: '20',
    PHOTO_INTERACTED: '21',
    CALL: '22',
    ACCEPT_CALL: '23',
    DECLINE_CALL: '24',
    CANCEL_CALL: '25',
    VIDEO_CALL: '26',
    ACCEPT_VIDEO_CALL: '27',
    DECLINE_VIDEO_CALL: '28',
    CANCEL_VIDEO_CALL: '29',
    MISS_CALL: '30',
    MISS_VIDEO_CALL: '31',
    FOLLOWING: '32',
    EXCHANGE: '33',
    FLUTTER_NOTIFICATION_CLICK: '34',
    SUBSCRIBE: '35',
    SEND_MEDIA_MESSAGE: '36',
    SEND_MESSAGE: '37',
    SEND_STICKER: '38',
    BUSY_CALL: '39',
    QNA_SEND_MESSAGE: '40',
    COMMENT_POST: '80',
    COMMENT_REPLY: '81',
    LIKE_POST: '82',
    LIKE_COMMENT: '83',
    CHANGE_PRICE_CONVERSATION: '84',
    SEND_SECRET_MESSAGE: '85',
    CREATE_POST: '86',
    DELETE_PACKAGE_SUBSRIBE: '87',
    DENY_POST: '88',
    DENY_SECRET_ALBUM: '89',
    USER_LIKE_POST: '90',
    USER_UNLIKE_POST: '91',
    WITHDRAW_SUCCESS: '92',
    WITHDRAW_DENY: '93',
    //   -----------------------------
    //   SEND_NOTIFICATION: "0",
    JOIN_POST_REQUEST: '1',
    DENY_REQUEST: '2',
    CANCEL_REQUEST: '3',
    ACCEPT_REQUEST: '4',
    //   CHAT: "5",
    //   CALL: "6",
    END_CALL: '6',
    FRIEND_REQUEST: '7',
    FRIEND_ACCEPT: '8',
    SUCCESS_MATCH: '9',
    QR_CODE_CANNING: '10',
    APPOINTMENT_PROBLEM: '11',
    GUEST_REGISTER_ACCEPT: '12',
    GUEST_REGISTER_DENY: '13',
    HOST_REGISTER_ACCEPT: '14',
    HOST_REGISTER_DENY: '15',
    MATCHING_SUCCESS: '16',
    MACHING_FAIL: '17',
    END_MEETING: '18',
    MATCHING_DEPLAY: '19',
    LATE: '20',
    EXTRA_TIME: '21',
    HOST_LATE: '22',
    GUEST_LATE: '23',
    CANCEL_REQUEST_ACCEPT: '24',
    DENY_REQUEST_ACCEPT: '25',
    REWARD: '26',
    REFUND: '27',
    DELETE_USER: '28',
    DELETE_POST: '29',
    //   BLOCK: "30",
    UNBLOCK: '31',
    VERIFY_IMAGE_SUCCESS: '32',
    VERIFY_IMAGE_FAIL: '33',
    SEND_REQUEST: '34',
    // WITHDRAW_SUCCESS: '35',
    VERIFY_NICE: '9999',
};

export const STATE = {
    DONE: 'DONE',
    STAGING: 'STAGING',
    INIT: 'INIT',
};

export const TIME_ZONE_OF_KOREAN = 9;

export const INTERACTING_TYPE = {
    USER_LIKE_POST: 'USER_LIKE_POST',
    USER_LIKE_COMMENT: 'USER_LIKE_COMMENT',
    USER_REPLY_COMMENT: 'USER_REPLY_COMMENT',
    USER_COMMENT_POST: 'USER_COMMENT_POST',
    CELEB_CREATE_POST: 'CELEB_CREATE_POST',
    CELEB_FOLLOW_CREATE_POST: 'CELEB_FOLLOW_CREATE_POST',
    CELEB_SUBSCRIBE_CREATE_POST: 'CELEB_SUBSCRIBE_CREATE_POST',
    DELETE_PACKAGE_SUBSRIBE: 'DELETE_PACKAGE_SUBSRIBE',
    OTHER_USER_FOLLOW_ME: 'OTHER_USER_FOLLOW_ME',
    OTHER_USER_SUBSCRIBE_ME: 'OTHER_USER_SUBSCRIBE_ME',
    SEND_SECRET_MESSAGE: 'SEND_SECRET_MESSAGE',
    CMS_SEND_NOTI: 'CMS_SEND_NOTI',
    CALL: 'CALL',
    SEND_STICKER: 'SEND_STICKER',
    SEND_GIFT: 'SEND_GIFT',
    ADMIN_DENY_POST: 'ADMIN_DENY_POST',
    ADMIN_DENY_SECRET_ALBUM: 'ADMIN_DENY_SECRET_ALBUM',
};

export const TYPE_REVENUE = {
    SUBSCRIBE: 'SUBSCRIBE',
    RE_SUBSCRIBE: 'RE_SUBSCRIBE',
    PAID_MESSAGE: 'PAID_MESSAGE',
    GIFT: 'GIFT',
    GIFT_FROM_VIDEO: 'GIFT_FROM_VIDEO',
    BUY_POST: 'BUY_POST',
    BUY_SECRET_ALBUM: 'BUY_SECRET_ALBUM',
    BUY_SECRET_MESSAGE: 'BUY_SECRET_MESSAGE',
    VIDEO_CALL: 'VIDEO_CALL',
    WITHDRAW: 'WITHDRAW',
    ADMIN_ADD_STAR: 'ADMIN_ADD_STAR',
    GIFT_FROM_CHAT: 'GIFT_FROM_CHAT',
    WITHDRAW_DENY: 'WITHDRAW_DENY'
};
export const TYPE_SUBSCRIBE = {
    SUBSCRIBE: 'SUBSCRIBE',
    UNSUBSCRIBE: 'UNSUBSCRIBE',
};

export const CLICK_ACTION = { FLUTTER_NOTIFICATION_CLICK: 'FLUTTER_NOTIFICATION_CLICK' };

export const CHAT = {
    CREATED: 'CREATED',
    SENT: 'SENT',
    CHATING: 'CHATING',
    END_CHAT: 'END_CHAT',
    DELETED: 'DELETED',
    REJECT: 'REJECT',
};

export const WITHDRAW = {
    LIMIT_CONDITION: 50000,
    STATE: {
        PROCESS: 'PROCESS',
        ACCEPT: 'ACCEPT',
        DENY: 'DENY',
        AGENCY_PENDING: 'AGENCY_PENDING',
        PENDING: 'PENDING',
    }
};

export const STATE_WITHDRAW = {
    PROCESS: 'PROCESS',
    ACCEPT: 'ACCEPT',
    DENY: 'DENY',
    AGENCY_PENDING: 'AGENCY_PENDING',
};

export const USER = {
    TYPE: {
        CELEBRITY: 'CELEBRITY',
        NORMAL: 'NORMAL',
        ADMIN: 'ADMIN'
    }
}
